### ISSUE TITLE
Migration error reporting is confusing

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [ariga/atlas-go-sdk#44]
If a migration fails, this module seems to silently report success.

Why?

Even if the `atlas` command returns a non-zero exit code, the `Apply` and similar methods always return a nil error, as long as it can parse the output of the command as JSON: https://github.com/ariga/atlas-go-sdk/blob/a226c45be16823f324ac93802ae940e0f1f42bba/atlasexec/atlas.go#L303-L307

It seems that API users have to check the `.Error` property on what one would expect to be the _success_ output to check for errors, in addition to the "normal" `error` return.

This is confusing and error-prone.

**Comment by giautm** [comment]
Hey @mgabeler-lee-6rs, thank you for your report. we changed the behavior and release new version v0.3.0. Please upgrade!
