### ISSUE TITLE
MigrateApply throws an error, even when the migrations are successful

### ISSUE THREAD

**Issue by muku2211** [ariga/atlas-go-sdk#47]
**Current version**: v0.3.0

For example, here's my code:
```
// Run `atlas migrate apply` on a SQLite database under /tmp.
res, err := client.MigrateApply(context.Background(), &atlasexec.MigrateApplyParams{
Env: "prod",
})

fmt.Println("res: ", res)
repr.Println(err)
```

I have exported the ATLAS_TOKEN, ATLAS_PROJECT and DATABASE_URL env vars.

Irrespective of whether the actual migration operation is successful or not, `res` is always `nil` and `err` is always populated with 
```
atlasexec.cliError{
  stdout: "...logs of what the 'atlas migrate apply' command outputs"
}
```

Expectation is that on successful migration (even if that means no new migration files are to be applied), the `res` variable should be populated with a useful success message & the `err` variable should be `nil`.

**Comment by giautm** [comment]
Hello @muku2211, can you give me more detail what is actually printed in the stdout?

**Comment by muku2211** [comment]
Hi @giautm , here's a sample output for `Println(err)`

```
atlasexec.cliError{
  stdout: "{\"Driver\":\"postgres\",\"URL\":{\"Scheme\":\"postgres\",\"Opaque\":\"\",\"User\":{},\"Host\":\"0.0.0.0:5432\",\"Path\":\"/tenant_local\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"search_path=public\\u0026sslmode=disable\",\"Fragment\":\"\",\"RawFragment\":\"\",\"Schema\":\"public\"},\"Current\":\"20231225071955\",\"Start\":\"2024-01-12T10:41:48.038779+05:30\",\"End\":\"2024-01-12T10:41:48.058348+05:30\",\"Message\":\"No migration files to execute\"}\n{\"Driver\":\"postgres\",\"URL\":{\"Scheme\":\"postgres\",\"Opaque\":\"\",\"User\":{},\"Host\":\"0.0.0.0:5432\",\"Path\":\"/tenant_test\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"search_path=public\\u0026sslmode=disable\",\"Fragment\":\"\",\"RawFragment\":\"\",\"Schema\":\"public\"},\"Current\":\"20231225071955\",\"Start\":\"2024-01-12T10:41:48.177624+05:30\",\"End\":\"2024-01-12T10:41:48.18117+05:30\",\"Message\":\"No migration files to execute\"}",
}
```

Here, I was expecting this to be returned in the `response`, not `err`.

**Comment by giautm** [comment]
Thank you, I'll fix this asap

**Comment by giautm** [comment]
Hey @muku2211, I just checked again the output. Look like you run atlas command for multiple tenants. So the result for each tenant was printed on a new line, and AtlasExec was unable to parse it into the response structure :-/

**Comment by muku2211** [comment]
Yes, that's right, I'm using it for multiple tenants, following the instructions outlined in this [blog](https://atlasgo.io/blog/2022/10/27/multi-tenant-support#multi-tenant-environments).

I just checked with a single database and it works as expected. So yes, the problem is with multiple databases

**Comment by giautm** [comment]
Hello @muku2211, we just release v0.4.0. From now on, you can use `MigrateApplySlice` to work with multiple databases. Cheer!!

Please let me know if you have any other issue,

**Comment by muku2211** [comment]
Awesome, will try it out and get back to you. Thanks a lot @giautm !
